-- Migration: Create REVIEWS table
-- Stores user reviews with embeddings for sentiment analysis

CREATE TABLE IF NOT EXISTS reviews (
    review_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    item_id UUID NOT NULL REFERENCES products(item_id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    transaction_id UUID NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE,

    -- Review content
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    review_title VARCHAR(500),
    review_text TEXT NOT NULL,
    review_stars INTEGER NOT NULL,
    manual_or_agent_generated VARCHAR(20) NOT NULL DEFAULT 'manual', -- 'manual' or 'agent'

    -- GenAI features
    embeddings vector(1536), -- Review embeddings for semantic search

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Constraints
    CONSTRAINT check_review_stars CHECK (review_stars >= 1 AND review_stars <= 5),
    CONSTRAINT check_manual_or_agent CHECK (manual_or_agent_generated IN ('manual', 'agent')),
    CONSTRAINT unique_review_per_transaction UNIQUE(transaction_id)
);

-- Indexes for reviews
CREATE INDEX IF NOT EXISTS idx_reviews_item_id ON reviews(item_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_transaction_id ON reviews(transaction_id);
CREATE INDEX IF NOT EXISTS idx_reviews_stars ON reviews(review_stars);
CREATE INDEX IF NOT EXISTS idx_reviews_embeddings ON reviews USING ivfflat(embeddings vector_cosine_ops) WITH (lists = 100);

-- Comments
COMMENT ON TABLE reviews IS 'User-generated reviews with AI-generated embeddings and sentiment';
COMMENT ON COLUMN reviews.embeddings IS 'Review text embeddings for sentiment analysis';
COMMENT ON COLUMN reviews.manual_or_agent_generated IS 'Indicates if review was written manually by user or generated by AI agent';
